package lila.common

object Region {

  sealed abstract class Province(val key: String, val name: String)
  object Province {
    case object Beijing extends Province("Beijing", "北京")
    case object Tianjin extends Province("Tianjin", "天津")
    case object Hebei extends Province("Hebei", "河北")
    case object Shanxi extends Province("Shanxi", "山西")
    case object Neimenggu extends Province("Neimenggu", "内蒙古")
    case object Liaoning extends Province("Liaoning", "辽宁")
    case object Jilin extends Province("Jilin", "吉林")
    case object Heilongjiang extends Province("Heilongjiang", "黑龙江")
    case object Shanghai extends Province("Shanghai", "上海")
    case object Jiangsu extends Province("Jiangsu", "江苏")
    case object Zhejiang extends Province("Zhejiang", "浙江")
    case object Anhui extends Province("Anhui", "安徽")
    case object Fujian extends Province("Fujian", "福建")
    case object Jiangxi extends Province("Jiangxi", "江西")
    case object Shandong extends Province("Shandong", "山东")
    case object Henan extends Province("Henan", "河南")
    case object Hubei extends Province("Hubei", "湖北")
    case object Hunan extends Province("Hunan", "湖南")
    case object Guangdong extends Province("Guangdong", "广东")
    case object Guangxi extends Province("Guangxi", "广西")
    case object Hainan extends Province("Hainan", "海南")
    case object Chongqing extends Province("Chongqing", "重庆")
    case object Sichuan extends Province("Sichuan", "四川")
    case object Guizhou extends Province("Guizhou", "贵州")
    case object Yunnan extends Province("Yunnan", "云南")
    case object Xizhang extends Province("Xizhang", "西藏")
    case object Shanxi2 extends Province("Shanxi2", "陕西")
    case object Gansu extends Province("Gansu", "甘肃")
    case object Qinghai extends Province("Qinghai", "青海")
    case object Ningxia extends Province("Ningxia", "宁夏")
    case object Xinjiang extends Province("Xinjiang", "新疆")
    case object Taiwan extends Province("Taiwan", "台湾")
    case object Hongkong extends Province("Hongkong", "香港")
    case object Macau extends Province("Macau", "澳门")

    val all = List(Beijing, Tianjin, Hebei, Shanxi, Neimenggu, Liaoning, Jilin, Heilongjiang, Shanghai, Jiangsu, Zhejiang, Anhui, Fujian, Jiangxi, Shandong, Henan, Hubei, Hunan, Guangdong, Guangxi, Hainan, Chongqing, Sichuan, Guizhou, Yunnan, Xizhang, Shanxi2, Gansu, Qinghai, Ningxia, Xinjiang, Taiwan, Hongkong, Macau)
    val keySet = all.map(_.key).toSet

    def provinces = all.map { c => (c.key -> c.name) }
    def byKey(key: String) = all.find(_.key == key) err s"Bad Province $key"
    def name(key: String) = byKey(key).name
  }

  case class CaseCity(key: String, name: String)
  sealed abstract class City(val key: String, val name: String, val province: String)
  object City {

    case object BeijingDongcheng extends City("BeijingDongcheng", "东城", "Beijing")
    case object BeijingXicheng extends City("BeijingXicheng", "西城", "Beijing")
    case object BeijingChaoyang extends City("BeijingChaoyang", "朝阳", "Beijing")
    case object BeijingFengtai extends City("BeijingFengtai", "丰台", "Beijing")
    case object BeijingShijingshan extends City("BeijingShijingshan", "石景山", "Beijing")
    case object BeijingHaidian extends City("BeijingHaidian", "海淀", "Beijing")
    case object BeijingMentougou extends City("BeijingMentougou", "门头沟", "Beijing")
    case object BeijingFangshan extends City("BeijingFangshan", "房山", "Beijing")
    case object BeijingTongzhou extends City("BeijingTongzhou", "通州", "Beijing")
    case object BeijingShunyi extends City("BeijingShunyi", "顺义", "Beijing")
    case object BeijingChangping extends City("BeijingChangping", "昌平", "Beijing")
    case object BeijingDaxing extends City("BeijingDaxing", "大兴", "Beijing")
    case object BeijingHuairou extends City("BeijingHuairou", "怀柔", "Beijing")
    case object BeijingPinggu extends City("BeijingPinggu", "平谷", "Beijing")
    case object BeijingMiyun extends City("BeijingMiyun", "密云", "Beijing")
    case object BeijingYanqing extends City("BeijingYanqing", "延庆", "Beijing")
    case object TianjinHeping extends City("TianjinHeping", "和平", "Tianjin")
    case object TianjinHedong extends City("TianjinHedong", "河东", "Tianjin")
    case object TianjinHexi extends City("TianjinHexi", "河西", "Tianjin")
    case object TianjinNankai extends City("TianjinNankai", "南开", "Tianjin")
    case object TianjinHebei extends City("TianjinHebei", "河北", "Tianjin")
    case object TianjinHongqiao extends City("TianjinHongqiao", "红桥", "Tianjin")
    case object TianjinDongli extends City("TianjinDongli", "东丽", "Tianjin")
    case object TianjinXiqing extends City("TianjinXiqing", "西青", "Tianjin")
    case object TianjinJinnan extends City("TianjinJinnan", "津南", "Tianjin")
    case object TianjinBeichen extends City("TianjinBeichen", "北辰", "Tianjin")
    case object TianjinWuqing extends City("TianjinWuqing", "武清", "Tianjin")
    case object TianjinBaodi extends City("TianjinBaodi", "宝坻", "Tianjin")
    case object TianjinBinhaixinqu extends City("TianjinBinhaixinqu", "滨海新区", "Tianjin")
    case object TianjinNinghe extends City("TianjinNinghe", "宁河", "Tianjin")
    case object TianjinJinghai extends City("TianjinJinghai", "静海", "Tianjin")
    case object TianjinJixian extends City("TianjinJixian", "蓟县", "Tianjin")
    case object HebeiShijiazhuang extends City("HebeiShijiazhuang", "石家庄", "Hebei")
    case object HebeiTangshan extends City("HebeiTangshan", "唐山", "Hebei")
    case object HebeiQinhuangdao extends City("HebeiQinhuangdao", "秦皇岛", "Hebei")
    case object HebeiHandan extends City("HebeiHandan", "邯郸", "Hebei")
    case object HebeiXingtai extends City("HebeiXingtai", "邢台", "Hebei")
    case object HebeiBaoding extends City("HebeiBaoding", "保定", "Hebei")
    case object HebeiZhangjiakou extends City("HebeiZhangjiakou", "张家口", "Hebei")
    case object HebeiChengde extends City("HebeiChengde", "承德", "Hebei")
    case object HebeiCangzhou extends City("HebeiCangzhou", "沧州", "Hebei")
    case object HebeiLangfang extends City("HebeiLangfang", "廊坊", "Hebei")
    case object HebeiHengshui extends City("HebeiHengshui", "衡水", "Hebei")
    case object ShanxiTaiyuan extends City("ShanxiTaiyuan", "太原", "Shanxi")
    case object ShanxiDatong extends City("ShanxiDatong", "大同", "Shanxi")
    case object ShanxiYangquan extends City("ShanxiYangquan", "阳泉", "Shanxi")
    case object ShanxiChangzhi extends City("ShanxiChangzhi", "长治", "Shanxi")
    case object ShanxiJincheng extends City("ShanxiJincheng", "晋城", "Shanxi")
    case object ShanxiShuozhou extends City("ShanxiShuozhou", "朔州", "Shanxi")
    case object ShanxiJinzhong extends City("ShanxiJinzhong", "晋中", "Shanxi")
    case object ShanxiYuncheng extends City("ShanxiYuncheng", "运城", "Shanxi")
    case object ShanxiXinzhou extends City("ShanxiXinzhou", "忻州", "Shanxi")
    case object ShanxiLinfen extends City("ShanxiLinfen", "临汾", "Shanxi")
    case object ShanxiLvliang extends City("ShanxiLvliang", "吕梁", "Shanxi")
    case object NeimengguHohhot extends City("NeimengguHohhot", "呼和浩特", "Neimenggu")
    case object NeimengguBaotou extends City("NeimengguBaotou", "包头", "Neimenggu")
    case object NeimengguWuhai extends City("NeimengguWuhai", "乌海", "Neimenggu")
    case object NeimengguChifeng extends City("NeimengguChifeng", "赤峰", "Neimenggu")
    case object NeimengguTongliao extends City("NeimengguTongliao", "通辽", "Neimenggu")
    case object NeimengguOrdos extends City("NeimengguOrdos", "鄂尔多斯", "Neimenggu")
    case object NeimengguHulunber extends City("NeimengguHulunber", "呼伦贝尔", "Neimenggu")
    case object NeimengguBayanNur extends City("NeimengguBayanNur", "巴彦淖尔", "Neimenggu")
    case object NeimengguUlanqab extends City("NeimengguUlanqab", "乌兰察布", "Neimenggu")
    case object NeimengguHinggan extends City("NeimengguHinggan", "兴安盟", "Neimenggu")
    case object NeimengguXilinGol extends City("NeimengguXilinGol", "锡林郭勒盟", "Neimenggu")
    case object NeimengguAlxa extends City("NeimengguAlxa", "阿拉善盟", "Neimenggu")
    case object LiaoningShenyang extends City("LiaoningShenyang", "沈阳", "Liaoning")
    case object LiaoningDalian extends City("LiaoningDalian", "大连", "Liaoning")
    case object LiaoningAnshan extends City("LiaoningAnshan", "鞍山", "Liaoning")
    case object LiaoningFushun extends City("LiaoningFushun", "抚顺", "Liaoning")
    case object LiaoningBenxi extends City("LiaoningBenxi", "本溪", "Liaoning")
    case object LiaoningDandong extends City("LiaoningDandong", "丹东", "Liaoning")
    case object LiaoningJinzhou extends City("LiaoningJinzhou", "锦州", "Liaoning")
    case object LiaoningYingkou extends City("LiaoningYingkou", "营口", "Liaoning")
    case object LiaoningFuxin extends City("LiaoningFuxin", "阜新", "Liaoning")
    case object LiaoningLiaoyang extends City("LiaoningLiaoyang", "辽阳", "Liaoning")
    case object LiaoningPanjin extends City("LiaoningPanjin", "盘锦", "Liaoning")
    case object LiaoningTieling extends City("LiaoningTieling", "铁岭", "Liaoning")
    case object LiaoningChaoyang extends City("LiaoningChaoyang", "朝阳", "Liaoning")
    case object LiaoningHuludao extends City("LiaoningHuludao", "葫芦岛", "Liaoning")
    case object LiaoningJinpuxinqu extends City("LiaoningJinpuxinqu", "金普新区", "Liaoning")
    case object JilinChangchun extends City("JilinChangchun", "长春", "Jilin")
    case object JilinJilin extends City("JilinJilin", "吉林", "Jilin")
    case object JilinSiping extends City("JilinSiping", "四平", "Jilin")
    case object JilinLiaoyuan extends City("JilinLiaoyuan", "辽源", "Jilin")
    case object JilinTonghua extends City("JilinTonghua", "通化", "Jilin")
    case object JilinBaishan extends City("JilinBaishan", "白山", "Jilin")
    case object JilinSongyuan extends City("JilinSongyuan", "松原", "Jilin")
    case object JilinBaicheng extends City("JilinBaicheng", "白城", "Jilin")
    case object JilinYanbian extends City("JilinYanbian", "延边", "Jilin")
    case object HeilongjiangHarbin extends City("HeilongjiangHarbin", "哈尔滨", "Heilongjiang")
    case object HeilongjiangQiqihar extends City("HeilongjiangQiqihar", "齐齐哈尔", "Heilongjiang")
    case object HeilongjiangJixi extends City("HeilongjiangJixi", "鸡西", "Heilongjiang")
    case object HeilongjiangHegang extends City("HeilongjiangHegang", "鹤岗", "Heilongjiang")
    case object HeilongjiangShuangyashan extends City("HeilongjiangShuangyashan", "双鸭山", "Heilongjiang")
    case object HeilongjiangDaqing extends City("HeilongjiangDaqing", "大庆", "Heilongjiang")
    case object HeilongjiangYichun extends City("HeilongjiangYichun", "伊春", "Heilongjiang")
    case object HeilongjiangJiamusi extends City("HeilongjiangJiamusi", "佳木斯", "Heilongjiang")
    case object HeilongjiangQitaihe extends City("HeilongjiangQitaihe", "七台河", "Heilongjiang")
    case object HeilongjiangMudanjiang extends City("HeilongjiangMudanjiang", "牡丹江", "Heilongjiang")
    case object HeilongjiangHeihe extends City("HeilongjiangHeihe", "黑河", "Heilongjiang")
    case object HeilongjiangSuihua extends City("HeilongjiangSuihua", "绥化", "Heilongjiang")
    case object HeilongjiangDaXingAnLing extends City("HeilongjiangDaXingAnLing", "大兴安岭", "Heilongjiang")
    case object ShanghaiHangpu extends City("ShanghaiHangpu", "黄浦", "Shanghai")
    case object ShanghaiXuhui extends City("ShanghaiXuhui", "徐汇", "Shanghai")
    case object ShanghaiChangning extends City("ShanghaiChangning", "长宁", "Shanghai")
    case object ShanghaiNingan extends City("ShanghaiNingan", "静安", "Shanghai")
    case object ShanghaiPutuo extends City("ShanghaiPutuo", "普陀", "Shanghai")
    case object ShanghaiZhabei extends City("ShanghaiZhabei", "闸北", "Shanghai")
    case object ShanghaiHongkou extends City("ShanghaiHongkou", "虹口", "Shanghai")
    case object ShanghaiYangpu extends City("ShanghaiYangpu", "杨浦", "Shanghai")
    case object ShanghaiMinhang extends City("ShanghaiMinhang", "闵行", "Shanghai")
    case object ShanghaiBaoshan extends City("ShanghaiBaoshan", "宝山", "Shanghai")
    case object ShanghaiJiading extends City("ShanghaiJiading", "嘉定", "Shanghai")
    case object ShanghaiPudong extends City("ShanghaiPudong", "浦东", "Shanghai")
    case object ShanghaiJinshan extends City("ShanghaiJinshan", "金山", "Shanghai")
    case object ShanghaiSongjiang extends City("ShanghaiSongjiang", "松江", "Shanghai")
    case object ShanghaiQingpu extends City("ShanghaiQingpu", "青浦", "Shanghai")
    case object ShanghaiFengxian extends City("ShanghaiFengxian", "奉贤", "Shanghai")
    case object ShanghaiChongming extends City("ShanghaiChongming", "崇明", "Shanghai")
    case object JiangsuNanjing extends City("JiangsuNanjing", "南京", "Jiangsu")
    case object JiangsuWuxi extends City("JiangsuWuxi", "无锡", "Jiangsu")
    case object JiangsuXuzhou extends City("JiangsuXuzhou", "徐州", "Jiangsu")
    case object JiangsuChangzhou extends City("JiangsuChangzhou", "常州", "Jiangsu")
    case object JiangsuSuzhou extends City("JiangsuSuzhou", "苏州", "Jiangsu")
    case object JiangsuNantong extends City("JiangsuNantong", "南通", "Jiangsu")
    case object JiangsuLianyungang extends City("JiangsuLianyungang", "连云港", "Jiangsu")
    case object JiangsuHuaian extends City("JiangsuHuaian", "淮安", "Jiangsu")
    case object JiangsuYancheng extends City("JiangsuYancheng", "盐城", "Jiangsu")
    case object JiangsuYangzhou extends City("JiangsuYangzhou", "扬州", "Jiangsu")
    case object JiangsuZhenjiang extends City("JiangsuZhenjiang", "镇江", "Jiangsu")
    case object JiangsuTaizhou extends City("JiangsuTaizhou", "泰州", "Jiangsu")
    case object JiangsuSuqian extends City("JiangsuSuqian", "宿迁", "Jiangsu")
    case object ZhejiangHangzhou extends City("ZhejiangHangzhou", "杭州", "Zhejiang")
    case object ZhejiangNingbo extends City("ZhejiangNingbo", "宁波", "Zhejiang")
    case object ZhejiangWenzhou extends City("ZhejiangWenzhou", "温州", "Zhejiang")
    case object ZhejiangJiaxing extends City("ZhejiangJiaxing", "嘉兴", "Zhejiang")
    case object ZhejiangHuzhou extends City("ZhejiangHuzhou", "湖州", "Zhejiang")
    case object ZhejiangShaoxing extends City("ZhejiangShaoxing", "绍兴", "Zhejiang")
    case object ZhejiangJinhua extends City("ZhejiangJinhua", "金华", "Zhejiang")
    case object ZhejiangQuzhou extends City("ZhejiangQuzhou", "衢州", "Zhejiang")
    case object ZhejiangZhoushan extends City("ZhejiangZhoushan", "舟山新区", "Zhejiang")
    case object ZhejiangTaizhou extends City("ZhejiangTaizhou", "台州", "Zhejiang")
    case object ZhejiangLishui extends City("ZhejiangLishui", "丽水", "Zhejiang")
    case object AnhuiHefei extends City("AnhuiHefei", "合肥", "Anhui")
    case object AnhuiWuhu extends City("AnhuiWuhu", "芜湖", "Anhui")
    case object AnhuiBengbu extends City("AnhuiBengbu", "蚌埠", "Anhui")
    case object AnhuiHuainan extends City("AnhuiHuainan", "淮南", "Anhui")
    case object AnhuiMaanshan extends City("AnhuiMaanshan", "马鞍山", "Anhui")
    case object AnhuiHuaibei extends City("AnhuiHuaibei", "淮北", "Anhui")
    case object AnhuiTongling extends City("AnhuiTongling", "铜陵", "Anhui")
    case object AnhuiAnqing extends City("AnhuiAnqing", "安庆", "Anhui")
    case object AnhuiHuangshan extends City("AnhuiHuangshan", "黄山", "Anhui")
    case object AnhuiChuzhou extends City("AnhuiChuzhou", "滁州", "Anhui")
    case object AnhuiFuyang extends City("AnhuiFuyang", "阜阳", "Anhui")
    case object AnhuiSuzhou extends City("AnhuiSuzhou", "宿州", "Anhui")
    case object AnhuiLuan extends City("AnhuiLuan", "六安", "Anhui")
    case object AnhuiBozhou extends City("AnhuiBozhou", "亳州", "Anhui")
    case object AnhuiChizhou extends City("AnhuiChizhou", "池州", "Anhui")
    case object AnhuiXuancheng extends City("AnhuiXuancheng", "宣城", "Anhui")
    case object FujianFuzhou extends City("FujianFuzhou", "福州", "Fujian")
    case object FujianXiamen extends City("FujianXiamen", "厦门", "Fujian")
    case object FujianPutian extends City("FujianPutian", "莆田", "Fujian")
    case object FujianSanming extends City("FujianSanming", "三明", "Fujian")
    case object FujianQuanzhou extends City("FujianQuanzhou", "泉州", "Fujian")
    case object FujianZhangzhou extends City("FujianZhangzhou", "漳州", "Fujian")
    case object FujianNanping extends City("FujianNanping", "南平", "Fujian")
    case object FujianLongyan extends City("FujianLongyan", "龙岩", "Fujian")
    case object FujianNingde extends City("FujianNingde", "宁德", "Fujian")
    case object JiangxiNanchang extends City("JiangxiNanchang", "南昌", "Jiangxi")
    case object JiangxiJingdezhen extends City("JiangxiJingdezhen", "景德镇", "Jiangxi")
    case object JiangxiPingxiang extends City("JiangxiPingxiang", "萍乡", "Jiangxi")
    case object JiangxiJiujiang extends City("JiangxiJiujiang", "九江", "Jiangxi")
    case object JiangxiXinyu extends City("JiangxiXinyu", "新余", "Jiangxi")
    case object JiangxiYingtan extends City("JiangxiYingtan", "鹰潭", "Jiangxi")
    case object JiangxiGanzhou extends City("JiangxiGanzhou", "赣州", "Jiangxi")
    case object JiangxiJian extends City("JiangxiJian", "吉安", "Jiangxi")
    case object JiangxiYichun extends City("JiangxiYichun", "宜春", "Jiangxi")
    case object JiangxiFuzhou extends City("JiangxiFuzhou", "抚州", "Jiangxi")
    case object JiangxiShangrao extends City("JiangxiShangrao", "上饶", "Jiangxi")
    case object ShandongJinan extends City("ShandongJinan", "济南", "Shandong")
    case object ShandongQingdao extends City("ShandongQingdao", "青岛", "Shandong")
    case object ShandongZibo extends City("ShandongZibo", "淄博", "Shandong")
    case object ShandongZaozhuang extends City("ShandongZaozhuang", "枣庄", "Shandong")
    case object ShandongDongying extends City("ShandongDongying", "东营", "Shandong")
    case object ShandongYantai extends City("ShandongYantai", "烟台", "Shandong")
    case object ShandongWeifang extends City("ShandongWeifang", "潍坊", "Shandong")
    case object ShandongJining extends City("ShandongJining", "济宁", "Shandong")
    case object ShandongTaian extends City("ShandongTaian", "泰安", "Shandong")
    case object ShandongWeihai extends City("ShandongWeihai", "威海", "Shandong")
    case object ShandongRizhao extends City("ShandongRizhao", "日照", "Shandong")
    case object ShandongLaiwu extends City("ShandongLaiwu", "莱芜", "Shandong")
    case object ShandongLinyi extends City("ShandongLinyi", "临沂", "Shandong")
    case object ShandongDezhou extends City("ShandongDezhou", "德州", "Shandong")
    case object ShandongLiaocheng extends City("ShandongLiaocheng", "聊城", "Shandong")
    case object ShandongBinzhou extends City("ShandongBinzhou", "滨州", "Shandong")
    case object ShandongHeze extends City("ShandongHeze", "菏泽", "Shandong")
    case object HenanZhengzhou extends City("HenanZhengzhou", "郑州", "Henan")
    case object HenanKaifeng extends City("HenanKaifeng", "开封", "Henan")
    case object HenanLuoyang extends City("HenanLuoyang", "洛阳", "Henan")
    case object HenanPingdingshan extends City("HenanPingdingshan", "平顶山", "Henan")
    case object HenanAnyang extends City("HenanAnyang", "安阳", "Henan")
    case object HenanHebi extends City("HenanHebi", "鹤壁", "Henan")
    case object HenanXinxiang extends City("HenanXinxiang", "新乡", "Henan")
    case object HenanJiaozuo extends City("HenanJiaozuo", "焦作", "Henan")
    case object HenanPuyang extends City("HenanPuyang", "濮阳", "Henan")
    case object HenanXuchang extends City("HenanXuchang", "许昌", "Henan")
    case object HenanLuohe extends City("HenanLuohe", "漯河", "Henan")
    case object HenanSanmenxia extends City("HenanSanmenxia", "三门峡", "Henan")
    case object HenanNanyang extends City("HenanNanyang", "南阳", "Henan")
    case object HenanShangqiu extends City("HenanShangqiu", "商丘", "Henan")
    case object HenanXinyang extends City("HenanXinyang", "信阳", "Henan")
    case object HenanZhoukou extends City("HenanZhoukou", "周口", "Henan")
    case object HenanZhumadian extends City("HenanZhumadian", "驻马店", "Henan")
    case object HubeiWuhan extends City("HubeiWuhan", "武汉", "Hubei")
    case object HubeiHuangshi extends City("HubeiHuangshi", "黄石", "Hubei")
    case object HubeiShiyan extends City("HubeiShiyan", "十堰", "Hubei")
    case object HubeiYichang extends City("HubeiYichang", "宜昌", "Hubei")
    case object HubeiXiangyang extends City("HubeiXiangyang", "襄阳", "Hubei")
    case object HubeiEzhou extends City("HubeiEzhou", "鄂州", "Hubei")
    case object HubeiJingmen extends City("HubeiJingmen", "荆门", "Hubei")
    case object HubeiXiaogan extends City("HubeiXiaogan", "孝感", "Hubei")
    case object HubeiJingzhou extends City("HubeiJingzhou", "荆州", "Hubei")
    case object HubeiHuanggang extends City("HubeiHuanggang", "黄冈", "Hubei")
    case object HubeiXianning extends City("HubeiXianning", "咸宁", "Hubei")
    case object HubeiSuizhou extends City("HubeiSuizhou", "随州", "Hubei")
    case object HubeiEnshi extends City("HubeiEnshi", "恩施", "Hubei")
    case object HunanChangsha extends City("HunanChangsha", "长沙", "Hunan")
    case object HunanZhuzhou extends City("HunanZhuzhou", "株洲", "Hunan")
    case object HunanXiangtan extends City("HunanXiangtan", "湘潭", "Hunan")
    case object HunanHengyang extends City("HunanHengyang", "衡阳", "Hunan")
    case object HunanShaoyang extends City("HunanShaoyang", "邵阳", "Hunan")
    case object HunanYueyang extends City("HunanYueyang", "岳阳", "Hunan")
    case object HunanChangde extends City("HunanChangde", "常德", "Hunan")
    case object HunanZhangjiajie extends City("HunanZhangjiajie", "张家界", "Hunan")
    case object HunanYiyang extends City("HunanYiyang", "益阳", "Hunan")
    case object HunanChenzhou extends City("HunanChenzhou", "郴州", "Hunan")
    case object HunanYongzhou extends City("HunanYongzhou", "永州", "Hunan")
    case object HunanHuaihua extends City("HunanHuaihua", "怀化", "Hunan")
    case object HunanLoudi extends City("HunanLoudi", "娄底", "Hunan")
    case object HunanXiangxi extends City("HunanXiangxi", "湘西", "Hunan")
    case object GuangdongGuangzhou extends City("GuangdongGuangzhou", "广州", "Guangdong")
    case object GuangdongShaoguan extends City("GuangdongShaoguan", "韶关", "Guangdong")
    case object GuangdongShenzhen extends City("GuangdongShenzhen", "深圳", "Guangdong")
    case object GuangdongZhuhai extends City("GuangdongZhuhai", "珠海", "Guangdong")
    case object GuangdongShantou extends City("GuangdongShantou", "汕头", "Guangdong")
    case object GuangdongFoshan extends City("GuangdongFoshan", "佛山", "Guangdong")
    case object GuangdongJiangmen extends City("GuangdongJiangmen", "江门", "Guangdong")
    case object GuangdongZhanjiang extends City("GuangdongZhanjiang", "湛江", "Guangdong")
    case object GuangdongMaoming extends City("GuangdongMaoming", "茂名", "Guangdong")
    case object GuangdongZhaoqing extends City("GuangdongZhaoqing", "肇庆", "Guangdong")
    case object GuangdongHuizhou extends City("GuangdongHuizhou", "惠州", "Guangdong")
    case object GuangdongMeizhou extends City("GuangdongMeizhou", "梅州", "Guangdong")
    case object GuangdongShanwei extends City("GuangdongShanwei", "汕尾", "Guangdong")
    case object GuangdongHeyuan extends City("GuangdongHeyuan", "河源", "Guangdong")
    case object GuangdongYangjiang extends City("GuangdongYangjiang", "阳江", "Guangdong")
    case object GuangdongQingyuan extends City("GuangdongQingyuan", "清远", "Guangdong")
    case object GuangdongDongguan extends City("GuangdongDongguan", "东莞", "Guangdong")
    case object GuangdongZhongshan extends City("GuangdongZhongshan", "中山", "Guangdong")
    case object GuangdongChaozhou extends City("GuangdongChaozhou", "潮州", "Guangdong")
    case object GuangdongJieyang extends City("GuangdongJieyang", "揭阳", "Guangdong")
    case object GuangdongYunfu extends City("GuangdongYunfu", "云浮", "Guangdong")
    case object GuangxiNanning extends City("GuangxiNanning", "南宁", "Guangxi")
    case object GuangxiLiuzhou extends City("GuangxiLiuzhou", "柳州", "Guangxi")
    case object GuangxiGuilin extends City("GuangxiGuilin", "桂林", "Guangxi")
    case object GuangxiWuzhou extends City("GuangxiWuzhou", "梧州", "Guangxi")
    case object GuangxiBeihai extends City("GuangxiBeihai", "北海", "Guangxi")
    case object GuangxiFangchenggang extends City("GuangxiFangchenggang", "防城港", "Guangxi")
    case object GuangxiQinzhou extends City("GuangxiQinzhou", "钦州", "Guangxi")
    case object GuangxiGuigang extends City("GuangxiGuigang", "贵港", "Guangxi")
    case object GuangxiYulin extends City("GuangxiYulin", "玉林", "Guangxi")
    case object GuangxiBaise extends City("GuangxiBaise", "百色", "Guangxi")
    case object GuangxiHezhou extends City("GuangxiHezhou", "贺州", "Guangxi")
    case object GuangxiHechi extends City("GuangxiHechi", "河池", "Guangxi")
    case object GuangxiLaibin extends City("GuangxiLaibin", "来宾", "Guangxi")
    case object GuangxiChongzuo extends City("GuangxiChongzuo", "崇左", "Guangxi")
    case object HainanHaikou extends City("HainanHaikou", "海口", "Hainan")
    case object HainanSanya extends City("HainanSanya", "三亚", "Hainan")
    case object HainanSansha extends City("HainanSansha", "三沙", "Hainan")
    case object ChongqingYuzhong extends City("ChongqingYuzhong", "渝中", "Chongqing")
    case object ChongqingJiangbei extends City("ChongqingJiangbei", "江北", "Chongqing")
    case object ChongqingNanan extends City("ChongqingNanan", "南岸", "Chongqing")
    case object ChongqingJiulongpo extends City("ChongqingJiulongpo", "九龙坡", "Chongqing")
    case object ChongqingShapingba extends City("ChongqingShapingba", "沙坪坝", "Chongqing")
    case object ChongqingDadukou extends City("ChongqingDadukou", "大渡口", "Chongqing")
    case object ChongqingBeibei extends City("ChongqingBeibei", "北碚", "Chongqing")
    case object ChongqingYubei extends City("ChongqingYubei", "渝北", "Chongqing")
    case object ChongqingBanan extends City("ChongqingBanan", "巴南", "Chongqing")
    case object SichuanChengdu extends City("SichuanChengdu", "成都", "Sichuan")
    case object SichuanZigong extends City("SichuanZigong", "自贡", "Sichuan")
    case object SichuanPanzhihua extends City("SichuanPanzhihua", "攀枝花", "Sichuan")
    case object SichuanLuzhou extends City("SichuanLuzhou", "泸州", "Sichuan")
    case object SichuanDeyang extends City("SichuanDeyang", "德阳", "Sichuan")
    case object SichuanMianyang extends City("SichuanMianyang", "绵阳", "Sichuan")
    case object SichuanGuangyuan extends City("SichuanGuangyuan", "广元", "Sichuan")
    case object SichuanSuining extends City("SichuanSuining", "遂宁", "Sichuan")
    case object SichuanNeijiang extends City("SichuanNeijiang", "内江", "Sichuan")
    case object SichuanLeshan extends City("SichuanLeshan", "乐山", "Sichuan")
    case object SichuanNanchong extends City("SichuanNanchong", "南充", "Sichuan")
    case object SichuanMeishan extends City("SichuanMeishan", "眉山", "Sichuan")
    case object SichuanYibin extends City("SichuanYibin", "宜宾", "Sichuan")
    case object SichuanGuangan extends City("SichuanGuangan", "广安", "Sichuan")
    case object SichuanDazhou extends City("SichuanDazhou", "达州", "Sichuan")
    case object SichuanYaan extends City("SichuanYaan", "雅安", "Sichuan")
    case object SichuanBazhong extends City("SichuanBazhong", "巴中", "Sichuan")
    case object SichuanZiyang extends City("SichuanZiyang", "资阳", "Sichuan")
    case object SichuanAba extends City("SichuanAba", "阿坝", "Sichuan")
    case object SichuanGarze extends City("SichuanGarze", "甘孜", "Sichuan")
    case object SichuanLiangshan extends City("SichuanLiangshan", "凉山", "Sichuan")
    case object GuizhouGuiyang extends City("GuizhouGuiyang", "贵阳", "Guizhou")
    case object GuizhouLiupanshui extends City("GuizhouLiupanshui", "六盘水", "Guizhou")
    case object GuizhouZunyi extends City("GuizhouZunyi", "遵义", "Guizhou")
    case object GuizhouAnshun extends City("GuizhouAnshun", "安顺", "Guizhou")
    case object GuizhouBijie extends City("GuizhouBijie", "毕节", "Guizhou")
    case object GuizhouTongren extends City("GuizhouTongren", "铜仁", "Guizhou")
    case object GuizhouQianxinan extends City("GuizhouQianxinan", "黔西南", "Guizhou")
    case object GuizhouQiandongnan extends City("GuizhouQiandongnan", "黔东南", "Guizhou")
    case object GuizhouQiannan extends City("GuizhouQiannan", "黔南", "Guizhou")
    case object YunnanKunming extends City("YunnanKunming", "昆明", "Yunnan")
    case object YunnanQujing extends City("YunnanQujing", "曲靖", "Yunnan")
    case object YunnanYuxi extends City("YunnanYuxi", "玉溪", "Yunnan")
    case object YunnanBaoshan extends City("YunnanBaoshan", "保山", "Yunnan")
    case object YunnanZhaotong extends City("YunnanZhaotong", "昭通", "Yunnan")
    case object YunnanLijiang extends City("YunnanLijiang", "丽江", "Yunnan")
    case object YunnanPuer extends City("YunnanPuer", "普洱", "Yunnan")
    case object YunnanLincang extends City("YunnanLincang", "临沧", "Yunnan")
    case object YunnanChuxiong extends City("YunnanChuxiong", "楚雄", "Yunnan")
    case object YunnanHonghe extends City("YunnanHonghe", "红河", "Yunnan")
    case object YunnanWenshan extends City("YunnanWenshan", "文山", "Yunnan")
    case object YunnanXishuangbanna extends City("YunnanXishuangbanna", "西双版纳", "Yunnan")
    case object YunnanDali extends City("YunnanDali", "大理", "Yunnan")
    case object YunnanDehong extends City("YunnanDehong", "德宏", "Yunnan")
    case object YunnanNujiang extends City("YunnanNujiang", "怒江", "Yunnan")
    case object YunnanDeqen extends City("YunnanDeqen", "迪庆", "Yunnan")
    case object XizhangLhasa extends City("XizhangLhasa", "拉萨", "Xizhang")
    case object XizhangRikaze extends City("XizhangRikaze", "日喀则", "Xizhang")
    case object XizhangQamdo extends City("XizhangQamdo", "昌都", "Xizhang")
    case object XizhangShannan extends City("XizhangShannan", "山南", "Xizhang")
    case object XizhangNagqu extends City("XizhangNagqu", "那曲", "Xizhang")
    case object XizhangNgari extends City("XizhangNgari", "阿里", "Xizhang")
    case object XizhangNyingchi extends City("XizhangNyingchi", "林芝", "Xizhang")
    case object Shanxi2Xian extends City("Shanxi2Xian", "西安", "Shanxi2")
    case object Shanxi2Tongchuan extends City("Shanxi2Tongchuan", "铜川", "Shanxi2")
    case object Shanxi2Baoji extends City("Shanxi2Baoji", "宝鸡", "Shanxi2")
    case object Shanxi2Xianyang extends City("Shanxi2Xianyang", "咸阳", "Shanxi2")
    case object Shanxi2Weinan extends City("Shanxi2Weinan", "渭南", "Shanxi2")
    case object Shanxi2Yanan extends City("Shanxi2Yanan", "延安", "Shanxi2")
    case object Shanxi2Hanzhong extends City("Shanxi2Hanzhong", "汉中", "Shanxi2")
    case object Shanxi2Yulin extends City("Shanxi2Yulin", "榆林", "Shanxi2")
    case object Shanxi2Ankang extends City("Shanxi2Ankang", "安康", "Shanxi2")
    case object Shanxi2Shangluo extends City("Shanxi2Shangluo", "商洛", "Shanxi2")
    case object Shanxi2Xixian extends City("Shanxi2Xixian", "西咸", "Shanxi2")
    case object GansuLanzhou extends City("GansuLanzhou", "兰州", "Gansu")
    case object GansuJiayuguan extends City("GansuJiayuguan", "嘉峪关", "Gansu")
    case object GansuJinchang extends City("GansuJinchang", "金昌", "Gansu")
    case object GansuBaiyin extends City("GansuBaiyin", "白银", "Gansu")
    case object GansuTianshui extends City("GansuTianshui", "天水", "Gansu")
    case object GansuWuwei extends City("GansuWuwei", "武威", "Gansu")
    case object GansuZhangye extends City("GansuZhangye", "张掖", "Gansu")
    case object GansuPingliang extends City("GansuPingliang", "平凉", "Gansu")
    case object GansuJiuquan extends City("GansuJiuquan", "酒泉", "Gansu")
    case object GansuQingyang extends City("GansuQingyang", "庆阳", "Gansu")
    case object GansuDingxi extends City("GansuDingxi", "定西", "Gansu")
    case object GansuLongnan extends City("GansuLongnan", "陇南", "Gansu")
    case object GansuLinxia extends City("GansuLinxia", "临夏", "Gansu")
    case object GansuGannan extends City("GansuGannan", "甘南", "Gansu")
    case object QinghaiXining extends City("QinghaiXining", "西宁", "Qinghai")
    case object QinghaiHaidong extends City("QinghaiHaidong", "海东", "Qinghai")
    case object QinghaiHaibei extends City("QinghaiHaibei", "海北", "Qinghai")
    case object QinghaiHuangnan extends City("QinghaiHuangnan", "黄南", "Qinghai")
    case object QinghaiHainan extends City("QinghaiHainan", "海南", "Qinghai")
    case object QinghaiGolog extends City("QinghaiGolog", "果洛", "Qinghai")
    case object QinghaiYushu extends City("QinghaiYushu", "玉树", "Qinghai")
    case object QinghaiHaixi extends City("QinghaiHaixi", "海西", "Qinghai")
    case object NingxiaYinchuan extends City("NingxiaYinchuan", "银川", "Ningxia")
    case object NingxiaShizuishan extends City("NingxiaShizuishan", "石嘴山", "Ningxia")
    case object NingxiaWuzhong extends City("NingxiaWuzhong", "吴忠", "Ningxia")
    case object NingxiaGuyuan extends City("NingxiaGuyuan", "固原", "Ningxia")
    case object NingxiaZhongwei extends City("NingxiaZhongwei", "中卫", "Ningxia")
    case object XinjiangUrumqi extends City("XinjiangUrumqi", "乌鲁木齐", "Xinjiang")
    case object XinjiangKaramay extends City("XinjiangKaramay", "克拉玛依", "Xinjiang")
    case object XinjiangTurpan extends City("XinjiangTurpan", "吐鲁番", "Xinjiang")
    case object XinjiangHami extends City("XinjiangHami", "哈密", "Xinjiang")
    case object XinjiangChangji extends City("XinjiangChangji", "昌吉", "Xinjiang")
    case object XinjiangBortala extends City("XinjiangBortala", "博尔塔拉", "Xinjiang")
    case object XinjiangBayingol extends City("XinjiangBayingol", "巴音郭楞", "Xinjiang")
    case object XinjiangAksu extends City("XinjiangAksu", "阿克苏", "Xinjiang")
    case object XinjiangKizilsu extends City("XinjiangKizilsu", "克孜勒苏", "Xinjiang")
    case object XinjiangKashgar extends City("XinjiangKashgar", "喀什", "Xinjiang")
    case object XinjiangHotan extends City("XinjiangHotan", "和田", "Xinjiang")
    case object XinjiangIli extends City("XinjiangIli", "伊犁", "Xinjiang")
    case object XinjiangQoqek extends City("XinjiangQoqek", "塔城", "Xinjiang")
    case object XinjiangAltay extends City("XinjiangAltay", "阿勒泰", "Xinjiang")
    case object TaiwanTaipei extends City("TaiwanTaipei", "台北", "Taiwan")
    case object TaiwanKaohsiung extends City("TaiwanKaohsiung", "高雄", "Taiwan")
    case object TaiwanKeelung extends City("TaiwanKeelung", "基隆", "Taiwan")
    case object TaiwanTaichung extends City("TaiwanTaichung", "台中", "Taiwan")
    case object TaiwanTainan extends City("TaiwanTainan", "台南", "Taiwan")
    case object TaiwanHsinchu extends City("TaiwanHsinchu", "新竹", "Taiwan")
    case object TaiwanChiayi extends City("TaiwanChiayi", "嘉义", "Taiwan")
    case object TaiwanNewTaipei extends City("TaiwanNewTaipei", "新北", "Taiwan")
    case object TaiwanYilan extends City("TaiwanYilan", "宜兰", "Taiwan")
    case object TaiwanTaoyuan extends City("TaiwanTaoyuan", "桃园", "Taiwan")
    case object TaiwanMiaoli extends City("TaiwanMiaoli", "苗栗", "Taiwan")
    case object TaiwanChanghua extends City("TaiwanChanghua", "彰化", "Taiwan")
    case object TaiwanNantou extends City("TaiwanNantou", "南投", "Taiwan")
    case object TaiwanYunlin extends City("TaiwanYunlin", "云林", "Taiwan")
    case object TaiwanPingtung extends City("TaiwanPingtung", "屏东", "Taiwan")
    case object TaiwanTaitung extends City("TaiwanTaitung", "台东", "Taiwan")
    case object TaiwanHualien extends City("TaiwanHualien", "花莲", "Taiwan")
    case object TaiwanPenghu extends City("TaiwanPenghu", "澎湖", "Taiwan")
    case object TaiwanJinmen extends City("TaiwanJinmen", "金门", "Taiwan")
    case object TaiwanLienchiang extends City("TaiwanLienchiang", "连江", "Taiwan")
    case object HongkongIsland extends City("HongKongIsland", "香港岛", "Hongkong")
    case object HongkongKowloon extends City("HongkongKowloon", "九龙", "Hongkong")
    case object HongkongNewTerritories extends City("HongkongNewTerritories", "新界", "Hongkong")
    case object MacauMacauPeninsula extends City("MacauMacauPeninsula", "澳门半岛", "Macau")
    case object MacauTaipa extends City("MacauTaipa", "氹仔岛", "Macau")
    case object MacauColoane extends City("MacauColoane", "路环岛", "Macau")

    val all = List(BeijingDongcheng, BeijingXicheng, BeijingChaoyang, BeijingFengtai, BeijingShijingshan, BeijingHaidian, BeijingMentougou, BeijingFangshan, BeijingTongzhou, BeijingShunyi, BeijingChangping, BeijingDaxing, BeijingHuairou, BeijingPinggu, BeijingMiyun, BeijingYanqing, TianjinHeping, TianjinHedong, TianjinHexi, TianjinNankai, TianjinHebei, TianjinHongqiao, TianjinDongli, TianjinXiqing, TianjinJinnan, TianjinBeichen, TianjinWuqing, TianjinBaodi, TianjinBinhaixinqu, TianjinNinghe, TianjinJinghai, TianjinJixian, HebeiShijiazhuang, HebeiTangshan, HebeiQinhuangdao, HebeiHandan, HebeiXingtai, HebeiBaoding, HebeiZhangjiakou, HebeiChengde, HebeiCangzhou, HebeiLangfang, HebeiHengshui, ShanxiTaiyuan, ShanxiDatong, ShanxiYangquan, ShanxiChangzhi, ShanxiJincheng, ShanxiShuozhou, ShanxiJinzhong, ShanxiYuncheng, ShanxiXinzhou, ShanxiLinfen, ShanxiLvliang, NeimengguHohhot, NeimengguBaotou, NeimengguWuhai, NeimengguChifeng, NeimengguTongliao, NeimengguOrdos, NeimengguHulunber, NeimengguBayanNur, NeimengguUlanqab, NeimengguHinggan, NeimengguXilinGol, NeimengguAlxa, LiaoningShenyang, LiaoningDalian, LiaoningAnshan, LiaoningFushun, LiaoningBenxi, LiaoningDandong, LiaoningJinzhou, LiaoningYingkou, LiaoningFuxin, LiaoningLiaoyang, LiaoningPanjin, LiaoningTieling, LiaoningChaoyang, LiaoningHuludao, LiaoningJinpuxinqu, JilinChangchun, JilinJilin, JilinSiping, JilinLiaoyuan, JilinTonghua, JilinBaishan, JilinSongyuan, JilinBaicheng, JilinYanbian, HeilongjiangHarbin, HeilongjiangQiqihar, HeilongjiangJixi, HeilongjiangHegang, HeilongjiangShuangyashan, HeilongjiangDaqing, HeilongjiangYichun, HeilongjiangJiamusi, HeilongjiangQitaihe, HeilongjiangMudanjiang, HeilongjiangHeihe, HeilongjiangSuihua, HeilongjiangDaXingAnLing, ShanghaiHangpu, ShanghaiXuhui, ShanghaiChangning, ShanghaiNingan, ShanghaiPutuo, ShanghaiZhabei, ShanghaiHongkou, ShanghaiYangpu, ShanghaiMinhang, ShanghaiBaoshan, ShanghaiJiading, ShanghaiPudong, ShanghaiJinshan, ShanghaiSongjiang, ShanghaiQingpu, ShanghaiFengxian, ShanghaiChongming, JiangsuNanjing, JiangsuWuxi, JiangsuXuzhou, JiangsuChangzhou, JiangsuSuzhou, JiangsuNantong, JiangsuLianyungang, JiangsuHuaian, JiangsuYancheng, JiangsuYangzhou, JiangsuZhenjiang, JiangsuTaizhou, JiangsuSuqian, ZhejiangHangzhou, ZhejiangNingbo, ZhejiangWenzhou, ZhejiangJiaxing, ZhejiangHuzhou, ZhejiangShaoxing, ZhejiangJinhua, ZhejiangQuzhou, ZhejiangZhoushan, ZhejiangTaizhou, ZhejiangLishui, AnhuiHefei, AnhuiWuhu, AnhuiBengbu, AnhuiHuainan, AnhuiMaanshan, AnhuiHuaibei, AnhuiTongling, AnhuiAnqing, AnhuiHuangshan, AnhuiChuzhou, AnhuiFuyang, AnhuiSuzhou, AnhuiLuan, AnhuiBozhou, AnhuiChizhou, AnhuiXuancheng, FujianFuzhou, FujianXiamen, FujianPutian, FujianSanming, FujianQuanzhou, FujianZhangzhou, FujianNanping, FujianLongyan, FujianNingde, JiangxiNanchang, JiangxiJingdezhen, JiangxiPingxiang, JiangxiJiujiang, JiangxiXinyu, JiangxiYingtan, JiangxiGanzhou, JiangxiJian, JiangxiYichun, JiangxiFuzhou, JiangxiShangrao, ShandongJinan, ShandongQingdao, ShandongZibo, ShandongZaozhuang, ShandongDongying, ShandongYantai, ShandongWeifang, ShandongJining, ShandongTaian, ShandongWeihai, ShandongRizhao, ShandongLaiwu, ShandongLinyi, ShandongDezhou, ShandongLiaocheng, ShandongBinzhou, ShandongHeze, HenanZhengzhou, HenanKaifeng, HenanLuoyang, HenanPingdingshan, HenanAnyang, HenanHebi, HenanXinxiang, HenanJiaozuo, HenanPuyang, HenanXuchang, HenanLuohe, HenanSanmenxia, HenanNanyang, HenanShangqiu, HenanXinyang, HenanZhoukou, HenanZhumadian, HubeiWuhan, HubeiHuangshi, HubeiShiyan, HubeiYichang, HubeiXiangyang, HubeiEzhou, HubeiJingmen, HubeiXiaogan, HubeiJingzhou, HubeiHuanggang, HubeiXianning, HubeiSuizhou, HubeiEnshi, HunanChangsha, HunanZhuzhou, HunanXiangtan, HunanHengyang, HunanShaoyang, HunanYueyang, HunanChangde, HunanZhangjiajie, HunanYiyang, HunanChenzhou, HunanYongzhou, HunanHuaihua, HunanLoudi, HunanXiangxi, GuangdongGuangzhou, GuangdongShaoguan, GuangdongShenzhen, GuangdongZhuhai, GuangdongShantou, GuangdongFoshan, GuangdongJiangmen, GuangdongZhanjiang, GuangdongMaoming, GuangdongZhaoqing, GuangdongHuizhou, GuangdongMeizhou, GuangdongShanwei, GuangdongHeyuan, GuangdongYangjiang, GuangdongQingyuan, GuangdongDongguan, GuangdongZhongshan, GuangdongChaozhou, GuangdongJieyang, GuangdongYunfu, GuangxiNanning, GuangxiLiuzhou, GuangxiGuilin, GuangxiWuzhou, GuangxiBeihai, GuangxiFangchenggang, GuangxiQinzhou, GuangxiGuigang, GuangxiYulin, GuangxiBaise, GuangxiHezhou, GuangxiHechi, GuangxiLaibin, GuangxiChongzuo, HainanHaikou, HainanSanya, HainanSansha, ChongqingYuzhong, ChongqingJiangbei, ChongqingNanan, ChongqingJiulongpo, ChongqingShapingba, ChongqingDadukou, ChongqingBeibei, ChongqingYubei, ChongqingBanan, SichuanChengdu, SichuanZigong, SichuanPanzhihua, SichuanLuzhou, SichuanDeyang, SichuanMianyang, SichuanGuangyuan, SichuanSuining, SichuanNeijiang, SichuanLeshan, SichuanNanchong, SichuanMeishan, SichuanYibin, SichuanGuangan, SichuanDazhou, SichuanYaan, SichuanBazhong, SichuanZiyang, SichuanAba, SichuanGarze, SichuanLiangshan, GuizhouGuiyang, GuizhouLiupanshui, GuizhouZunyi, GuizhouAnshun, GuizhouBijie, GuizhouTongren, GuizhouQianxinan, GuizhouQiandongnan, GuizhouQiannan, YunnanKunming, YunnanQujing, YunnanYuxi, YunnanBaoshan, YunnanZhaotong, YunnanLijiang, YunnanPuer, YunnanLincang, YunnanChuxiong, YunnanHonghe, YunnanWenshan, YunnanXishuangbanna, YunnanDali, YunnanDehong, YunnanNujiang, YunnanDeqen, XizhangLhasa, XizhangRikaze, XizhangQamdo, XizhangShannan, XizhangNagqu, XizhangNgari, XizhangNyingchi, Shanxi2Xian, Shanxi2Tongchuan, Shanxi2Baoji, Shanxi2Xianyang, Shanxi2Weinan, Shanxi2Yanan, Shanxi2Hanzhong, Shanxi2Yulin, Shanxi2Ankang, Shanxi2Shangluo, Shanxi2Xixian, GansuLanzhou, GansuJiayuguan, GansuJinchang, GansuBaiyin, GansuTianshui, GansuWuwei, GansuZhangye, GansuPingliang, GansuJiuquan, GansuQingyang, GansuDingxi, GansuLongnan, GansuLinxia, GansuGannan, QinghaiXining, QinghaiHaidong, QinghaiHaibei, QinghaiHuangnan, QinghaiHainan, QinghaiGolog, QinghaiYushu, QinghaiHaixi, NingxiaYinchuan, NingxiaShizuishan, NingxiaWuzhong, NingxiaGuyuan, NingxiaZhongwei, XinjiangUrumqi, XinjiangKaramay, XinjiangTurpan, XinjiangHami, XinjiangChangji, XinjiangBortala, XinjiangBayingol, XinjiangAksu, XinjiangKizilsu, XinjiangKashgar, XinjiangHotan, XinjiangIli, XinjiangQoqek, XinjiangAltay, TaiwanTaipei, TaiwanKaohsiung, TaiwanKeelung, TaiwanTaichung, TaiwanTainan, TaiwanHsinchu, TaiwanChiayi, TaiwanNewTaipei, TaiwanYilan, TaiwanTaoyuan, TaiwanMiaoli, TaiwanChanghua, TaiwanNantou, TaiwanYunlin, TaiwanPingtung, TaiwanTaitung, TaiwanHualien, TaiwanPenghu, TaiwanJinmen, TaiwanLienchiang, HongkongIsland, HongkongKowloon, HongkongNewTerritories, MacauMacauPeninsula, MacauTaipa, MacauColoane)
    val keySet = all.map(_.key).toSet

    def citys(provinceKey: String) = all.filter(_.province == provinceKey) map { c => (c.key -> c.name) }
    def caseCitys(provinceKey: String) = all.filter(_.province == provinceKey) map { c => CaseCity(c.key, c.name) }
    def byKey(key: String) = all.find(_.key == key) err s"Bad City $key"
    def name(key: String) = byKey(key).name

  }

}
